"""
This type stub file was generated by pyright.
"""

"""
Compatibility tools for differences between Python 2 and 3
"""
asunicode = ...
PYTHON_IMPL_WASM = ...
__all__ = ["asunicode", "asstr", "asbytes", "lmap", "lzip", "lrange", "lfilter", "with_metaclass", "PYTHON_IMPL_WASM"]
def asbytes(s): # -> bytes:
    ...

def asstr(s): # -> str:
    ...

def lrange(*args, **kwargs): # -> list[int]:
    ...

def lzip(*args, **kwargs): # -> list[tuple[Any, ...]]:
    ...

def lmap(*args, **kwargs): # -> list[Any]:
    ...

def lfilter(*args, **kwargs): # -> list[Any]:
    ...

def with_metaclass(meta, *bases): # -> metaclass:
    """Create a base class with a metaclass."""
    class metaclass(meta):
        ...
