"""
This type stub file was generated by pyright.
"""

from statsmodels.tools._test_runner import PytestTester
from .empirical_distribution import ECDF, ECDFDiscrete, StepFunction, monotone_fn_inverter
from .edgeworth import ExpandedNormal
from .discrete import genpoisson_p, zigenpoisson, zinegbin, zipoisson

__all__ = ['ECDF', 'ECDFDiscrete', 'ExpandedNormal', 'StepFunction', 'genpoisson_p', 'monotone_fn_inverter', 'test', 'zigenpoisson', 'zinegbin', 'zipoisson']
test = ...
