"""
This type stub file was generated by pyright.
"""

__all__ = ["abline_plot", "beanplot", "fboxplot", "hdrboxplot", "influence_plot", "interaction_plot", "mean_diff_plot", "plot_ccpr", "plot_ccpr_grid", "plot_corr", "plot_corr_grid", "plot_fit", "plot_leverage_resid2", "plot_partregress", "plot_partregress_grid", "plot_regress_exog", "qqplot", "rainbow", "rainbowplot", "tsa", "violinplot"]
