# See https://pre-commit.com for more information
default_install_hook_types:
  - commit-msg
  - pre-commit
  - pre-push

# global unformatted files
exclude: 'docs/.*\.docx'

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      # plaintext fixers
      - id: trailing-whitespace
        exclude: '\.log$'
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: mixed-line-ending
        args: [--fix, lf]
      # config syntax checkers
      - id: check-yaml
      - id: check-toml
      # filesystems checkers
      - id: check-symlinks
      - id: check-executables-have-shebangs

  # Markdown formatter
  - repo: https://github.com/hukkin/mdformat
    rev: 0.7.22
    hooks:
      - id: mdformat
        # https://mdformat.readthedocs.io/en/stable/users/plugins.html
        additional_dependencies:
          - mdformat-footnote
          - mdformat-gfm
          - mdformat-gfm-alerts
          - mdformat-ruff
          - mdformat-shfmt
        exclude: 'LICENSE\.md'

  # LaTeX formatter
  - repo: https://github.com/WGUNDERWOOD/tex-fmt
    rev: v0.5.4
    hooks:
      - id: tex-fmt

  # Python formatter
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.13
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  # Python type-checker
  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.402
    hooks:
    - id: pyright
      additional_dependencies:
        - matplotlib
        - polars
        - scapy
