"""
This type stub file was generated by pyright.
"""

from . import norms
from .scale import Huber, HuberScale, hubers_scale, mad
from statsmodels.tools._test_runner import PytestTester

"""
Robust statistical models
"""
__all__ = ["norms", "mad", "Huber", "HuberScale", "hubers_scale", "test"]
test = ...
