"""
This type stub file was generated by pyright.
"""

from typing import Any
from collections.abc import Sequence

"""
Functions that are general enough to use for any model fitting. The idea is
to untie these from LikelihoodModel so that they may be re-used generally.
"""
def check_kwargs(kwargs: dict[str, Any], allowed: Sequence[str], method: str): # -> None:
    ...

class Optimizer:
    ...
