"""
This type stub file was generated by pyright.
"""

"""
Created on Thu Aug 30 12:26:38 2012
Author: Josef Perktold


function jc =  c_sja(n,p)
% PURPOSE: find critical values for Johansen maximum eigenvalue statistic
% ------------------------------------------------------------
% USAGE:  jc = c_sja(n,p)
% where:    n = dimension of the VAR system
%           p = order of time polynomial in the null-hypothesis
%                 p = -1, no deterministic part
%                 p =  0, for constant term
%                 p =  1, for constant plus time-trend
%                 p >  1  returns no critical values
% ------------------------------------------------------------
% RETURNS: a (3x1) vector of percentiles for the maximum eigenvalue
%          statistic for: [90% 95% 99%]
% ------------------------------------------------------------
% NOTES: for n > 12, the function returns a (3x1) vector of zeros.
%        The values returned by the function were generated using
%        a method described in MacKinnon (1996), using his FORTRAN
%        program johdist.f
% ------------------------------------------------------------
% SEE ALSO: johansen()
% ------------------------------------------------------------
% References: MacKinnon, Haug, Michelis (1996) 'Numerical distribution
% functions of likelihood ratio tests for cointegration',
% Queen's University Institute for Economic Research Discussion paper.
% -------------------------------------------------------
% written by:
% James P. LeSage, Dept of Economics
% University of Toledo
% 2801 W. Bancroft St,
% Toledo, OH 43606
% jlesage@spatial-econometrics.com

"""
ss_ejcp0 = ...
ss_ejcp1 = ...
ss_ejcp2 = ...
ejcp0 = ...
ejcp1 = ...
ejcp2 = ...
def c_sja(n, p): # -> _Array[tuple[int], Any] | ndarray[_AnyShape, dtype[Any]]:
    ...

ss_tjcp0 = ...
ss_tjcp1 = ...
ss_tjcp2 = ...
tjcp0 = ...
tjcp1 = ...
tjcp2 = ...
def c_sjt(n, p): # -> _Array[tuple[int], Any] | ndarray[_AnyShape, dtype[Any]]:
    ...

if __name__ == '__main__':
    ...
