"""
This type stub file was generated by pyright.
"""

import os

class Colorizer:
    def __init__(self, style, colors, debug=...) -> None:
        ...

    def colorize_traceback(self, type, value, tb): # -> None:
        ...

    @property
    def stream(self): # -> TextIO | Any:
        ...



def add_hook(always: bool=..., style: str=..., colors: int=..., debug: bool=...) -> None:
    ...

def add_hook(always: bool=..., style: str=..., colors: int=..., debug: bool=...) -> None:
    ...
