"""
This type stub file was generated by pyright.
"""

import warnings
from statsmodels.compat.patsy import monkey_patch_cat_dtype
from statsmodels._version import __version__, __version_tuple__

__version_info__ = __version_tuple__
debug_warnings = ...
if debug_warnings:
    ...
def test(extra_args=..., exit=...): # -> bool:
    """
    Run the test suite

    Parameters
    ----------
    extra_args : list[str]
        List of argument to pass to pytest when running the test suite. The
        default is ['--tb=short', '--disable-pytest-warnings'].
    exit : bool
        Flag indicating whether the test runner should exit when finished.

    Returns
    -------
    int
        The status code from the test run if exit is False.
    """
    ...

__all__ = ["__version__", "__version_info__", "__version_tuple__", "test"]
