

import sys
from .dpkt import *
from . import ah, aim, aoe, arp, asn1, bgp, cdp, dhcp, diameter, dns, dtp, esp, ethernet, gre, gzip, h225, hsrp, http, http2, icmp, icmp6, ieee80211, igmp, ip, ip6, ipx, llc, loopback, mrt, netbios, netflow, ntp, ospf, pcap, pcapng, pim, pmap, ppp, pppoe, qq, radiotap, radius, rfb, rip, rpc, rtp, rx, sccp, sctp, sip, sll, sll2, smb, ssl, stp, stun, tcp, telnet, tftp, tns, tpkt, udp, vrrp, yahoo

"""fast, simple packet creation and parsing."""
__author__ = ...
__author_email__ = ...
__license__ = ...
__url__ = ...
__version__ = ...
