"""
This type stub file was generated by pyright.
"""

from . import dpkt

"""Authentication Header."""
class AH(dpkt.Packet):
    """Authentication Header.

    The Authentication Header (AH) protocol provides data origin authentication, data integrity, and replay protection.

    Attributes:
        __hdr__: Header fields of AH.
        auth: Authentication body.
        data: Message data.
    """
    __hdr__ = ...
    auth = ...
    def unpack(self, buf): # -> None:
        ...
    
    def __len__(self):
        ...
    
    def __bytes__(self): # -> bytes:
        ...
    


def test_default_creation(): # -> None:
    ...

def test_creation_from_buf(): # -> None:
    ...

