"""
This type stub file was generated by pyright.
"""

from . import dpkt

"""AOL Instant Messenger."""
class FLAP(dpkt.Packet):
    """Frame Layer Protocol.

    See more about the FLAP on
    https://en.wikipedia.org/wiki/OSCAR_protocol#FLAP_header

    Attributes:
        __hdr__: Header fields of FLAP.
        data: Message data.
    """
    __hdr__ = ...
    def unpack(self, buf): # -> None:
        ...
    


class SNAC(dpkt.Packet):
    """Simple Network Atomic Communication.

    See more about the SNAC on
    https://en.wikipedia.org/wiki/OSCAR_protocol#SNAC_data

    Attributes:
        __hdr__: Header fields of SNAC.
    """
    __hdr__ = ...


def tlv(buf): # -> tuple[Any, Any, Any, Any]:
    ...

def testAIM(): # -> None:
    ...

def testExceptions(): # -> None:
    ...

