

from . import dpkt

"""ATA over Ethernet Protocol."""
class AOE(dpkt.Packet):

    __hdr__ = ...
    __bit_fields__ = ...
    _cmdsw = ...
    @classmethod
    def set_cmd(cls, cmd, pktclass): # -> None:
        ...

    @classmethod
    def get_cmd(cls, cmd):
        ...

    def unpack(self, buf): # -> None:
        ...



AOE_CMD_ATA = ...
AOE_CMD_CFG = ...
AOE_FLAG_RSP = ...
def test_creation(): # -> None:
    ...

def test_properties(): # -> None:
    ...

def test_unpack(): # -> None:
    ...

def test_cmds(): # -> None:
    ...

def test_cmd_loading(): # -> None:
    ...
