"""
This type stub file was generated by pyright.
"""

from . import dpkt

"""ATA over Ethernet ATA command"""
ATA_DEVICE_IDENTIFY = ...
class AOEATA(dpkt.Packet):
    """ATA over Ethernet ATA command.

    See more about the AOEATA on
    https://en.wikipedia.org/wiki/ATA_over_Ethernet

    Attributes:
        __hdr__: Header fields of AOEATA.
        data: Message data.
    """
    __hdr__ = ...


def test_aoeata(): # -> None:
    ...

