"""
This type stub file was generated by pyright.
"""

from . import dpkt

"""ATA over Ethernet ATA command"""
class AOECFG(dpkt.Packet):
    """ATA over Ethernet ATA command.

    See more about the AOE on \
    https://en.wikipedia.org/wiki/ATA_over_Ethernet

    Attributes:
        __hdr__: Header fields of AOECFG.
        data: Message data.
    """
    __hdr__ = ...


def test_aoecfg(): # -> None:
    ...

