"""
This type stub file was generated by pyright.
"""

import sys

if sys.version_info < (3, ):
    ...
else:
    def compat_ord(char):
        ...
    
compat_izip = ...
if sys.version_info < (3, ):
    ...
else:
    def iteritems(d, **kw):
        ...
    
    intround = ...
def ntole(v): # -> Any:
    """convert a 2-byte word from the network byte order (big endian) to little endian;
    replaces socket.ntohs() to work on both little and big endian architectures
    """
    ...

def ntole64(v): # -> Any:
    """
    Convert an 8-byte word from network byte order (big endian) to little endian.
    """
    ...

def isstr(s): # -> bool:
    """True if 's' is an instance of basestring in py2, or of str in py3"""
    ...

