"""
This type stub file was generated by pyright.
"""

crc32c_table = ...
def add(crc, buf):
    ...

def done(crc):
    ...

def cksum(buf): # -> int:
    """Return computed CRC-32c checksum."""
    ...

def test_crc32c(): # -> None:
    ...

