

from . import dpkt

"""ITU-T H.225.0 Call Signaling."""
ALERTING = ...
CALL_PROCEEDING = ...
CONNECT = ...
CONNECT_ACKNOWLEDGE = ...
PROGRESS = ...
SETUP = ...
SETUP_ACKNOWLEDGE = ...
RESUME = ...
RESUME_ACKNOWLEDGE = ...
RESUME_REJECT = ...
SUSPEND = ...
SUSPEND_ACKNOWLEDGE = ...
SUSPEND_REJECT = ...
USER_INFORMATION = ...
DISCONNECT = ...
RELEASE = ...
RELEASE_COMPLETE = ...
RESTART = ...
RESTART_ACKNOWLEDGE = ...
SEGMENT = ...
CONGESTION_CONTROL = ...
INFORMATION = ...
NOTIFY = ...
STATUS = ...
STATUS_ENQUIRY = ...
RESERVED = ...
SHIFT = ...
CONGESTION_LEVEL = ...
REPEAT_INDICATOR = ...
MORE_DATA = ...
SENDING_COMPLETE = ...
SEGMENTED_MESSAGE = ...
BEARER_CAPABILITY = ...
CAUSE = ...
CALL_IDENTITY = ...
CALL_STATE = ...
CHANNEL_IDENTIFICATION = ...
PROGRESS_INDICATOR = ...
NETWORK_SPECIFIC_FACILITIES = ...
NOTIFICATION_INDICATOR = ...
DISPLAY = ...
DATE_TIME = ...
KEYPAD_FACILITY = ...
SIGNAL = ...
INFORMATION_RATE = ...
END_TO_END_TRANSIT_DELAY = ...
TRANSIT_DELAY_SELECTION_AND_INDICATION = ...
PACKET_LAYER_BINARY_PARAMETERS = ...
PACKET_LAYER_WINDOW_SIZE = ...
PACKET_SIZE = ...
CLOSED_USER_GROUP = ...
REVERSE_CHARGE_INDICATION = ...
CALLING_PARTY_NUMBER = ...
CALLING_PARTY_SUBADDRESS = ...
CALLED_PARTY_NUMBER = ...
CALLED_PARTY_SUBADDRESS = ...
REDIRECTING_NUMBER = ...
TRANSIT_NETWORK_SELECTION = ...
RESTART_INDICATOR = ...
LOW_LAYER_COMPATIBILITY = ...
HIGH_LAYER_COMPATIBILITY = ...
USER_TO_USER = ...
ESCAPE_FOR_EXTENSION = ...
class H225(dpkt.Packet):

    __hdr__ = ...
    def unpack(self, buf): # -> None:
        ...

    def __len__(self):
        ...

    def __bytes__(self): # -> bytes:
        ...

    class IE(dpkt.Packet):
        __hdr__ = ...
        def unpack(self, buf): # -> None:
            ...

        def __len__(self):
            ...

        def __bytes__(self): # -> bytes:
            ...





__s = ...
def test_pack(): # -> None:
    ...

def test_unpack(): # -> None:
    ...

def test_tpkt_unpack_errors(): # -> None:
    ...

def test_unpack_ie(): # -> None:
    ...
