

from . import dpkt

"""Internet Control Message Protocol for IPv6."""
ICMP6_DST_UNREACH = ...
ICMP6_PACKET_TOO_BIG = ...
ICMP6_TIME_EXCEEDED = ...
ICMP6_PARAM_PROB = ...
ICMP6_ECHO_REQUEST = ...
ICMP6_ECHO_REPLY = ...
MLD_LISTENER_QUERY = ...
MLD_LISTENER_REPORT = ...
MLD_LISTENER_DONE = ...
ICMP6_MEMBERSHIP_QUERY = ...
ICMP6_MEMBERSHIP_REPORT = ...
ICMP6_MEMBERSHIP_REDUCTION = ...
ND_ROUTER_SOLICIT = ...
ND_ROUTER_ADVERT = ...
ND_NEIGHBOR_SOLICIT = ...
ND_NEIGHBOR_ADVERT = ...
ND_REDIRECT = ...
ICMP6_ROUTER_RENUMBERING = ...
ICMP6_WRUREQUEST = ...
ICMP6_WRUREPLY = ...
ICMP6_FQDN_QUERY = ...
ICMP6_FQDN_REPLY = ...
ICMP6_NI_QUERY = ...
ICMP6_NI_REPLY = ...
ICMP6_MAXTYPE = ...
class ICMP6(dpkt.Packet):

    __hdr__ = ...
    class Error(dpkt.Packet):
        __hdr__ = ...
        def unpack(self, buf): # -> None:
            ...



    class Unreach(Error):
        ...


    class TooBig(Error):
        __hdr__ = ...


    class TimeExceed(Error):
        ...


    class ParamProb(Error):
        __hdr__ = ...


    class Echo(dpkt.Packet):
        __hdr__ = ...


    _typesw = ...
    def unpack(self, buf): # -> None:
        ...
