"""
This type stub file was generated by pyright.
"""

from . import dpkt

"""Internet Group Management Protocol."""
class IGMP(dpkt.Packet):
    """Internet Group Management Protocol.

    TODO: Longer class information....

    Attributes:
        __hdr__: Header fields of IGMP.
        TODO.
    """
    __hdr__ = ...
    def __bytes__(self): # -> bytes:
        ...
    


def test_construction_no_sum(): # -> None:
    ...

def test_construction_sum_set(): # -> None:
    ...

