

from . import dpkt

"""Internet Protocol."""
_ip_proto_names = ...
def get_ip_proto_name(p): # -> None:
    ...

class IP(dpkt.Packet):

    __hdr__ = ...
    __bit_fields__ = ...
    __pprint_funcs__ = ...
    _protosw = ...
    opts = ...
    def __init__(self, *args, **kwargs) -> None:
        ...

    def __len__(self):
        ...

    def __bytes__(self): # -> bytes:
        ...

    def unpack(self, buf): # -> None:
        ...

    @property
    def src(self) -> bytes:
        ...

    @property
    def dst(self) -> bytes:
        ...

    @property
    def p(self) -> int:
        ...

    @classmethod
    def set_proto(cls, p, pktclass): # -> None:
        ...

    @classmethod
    def get_proto(cls, p):
        ...

    @property
    def off(self):
        ...

    @off.setter
    def off(self, val): # -> None:
        ...



IP_ADDR_LEN = ...
IP_ADDR_BITS = ...
IP_HDR_LEN = ...
IP_OPT_LEN = ...
IP_OPT_LEN_MAX = ...
IP_HDR_LEN_MAX = ...
IP_LEN_MAX = ...
IP_LEN_MIN = ...
IP_ADDR_ANY = ...
IP_ADDR_BROADCAST = ...
IP_ADDR_LOOPBACK = ...
IP_ADDR_MCAST_ALL = ...
IP_ADDR_MCAST_LOCAL = ...
IP_TOS_DEFAULT = ...
IP_TOS_LOWDELAY = ...
IP_TOS_THROUGHPUT = ...
IP_TOS_RELIABILITY = ...
IP_TOS_LOWCOST = ...
IP_TOS_ECT = ...
IP_TOS_CE = ...
IP_TOS_PREC_ROUTINE = ...
IP_TOS_PREC_PRIORITY = ...
IP_TOS_PREC_IMMEDIATE = ...
IP_TOS_PREC_FLASH = ...
IP_TOS_PREC_FLASHOVERRIDE = ...
IP_TOS_PREC_CRITIC_ECP = ...
IP_TOS_PREC_INTERNETCONTROL = ...
IP_TOS_PREC_NETCONTROL = ...
IP_RF = ...
IP_DF = ...
IP_MF = ...
IP_OFFMASK = ...
IP_TTL_DEFAULT = ...
IP_TTL_MAX = ...
IP_PROTO_IP = ...
IP_PROTO_HOPOPTS = ...
IP_PROTO_ICMP = ...
IP_PROTO_IGMP = ...
IP_PROTO_GGP = ...
IP_PROTO_IPIP = ...
IP_PROTO_ST = ...
IP_PROTO_TCP = ...
IP_PROTO_CBT = ...
IP_PROTO_EGP = ...
IP_PROTO_IGP = ...
IP_PROTO_BBNRCC = ...
IP_PROTO_NVP = ...
IP_PROTO_PUP = ...
IP_PROTO_ARGUS = ...
IP_PROTO_EMCON = ...
IP_PROTO_XNET = ...
IP_PROTO_CHAOS = ...
IP_PROTO_UDP = ...
IP_PROTO_MUX = ...
IP_PROTO_DCNMEAS = ...
IP_PROTO_HMP = ...
IP_PROTO_PRM = ...
IP_PROTO_IDP = ...
IP_PROTO_TRUNK1 = ...
IP_PROTO_TRUNK2 = ...
IP_PROTO_LEAF1 = ...
IP_PROTO_LEAF2 = ...
IP_PROTO_RDP = ...
IP_PROTO_IRTP = ...
IP_PROTO_TP = ...
IP_PROTO_NETBLT = ...
IP_PROTO_MFPNSP = ...
IP_PROTO_MERITINP = ...
IP_PROTO_SEP = ...
IP_PROTO_3PC = ...
IP_PROTO_IDPR = ...
IP_PROTO_XTP = ...
IP_PROTO_DDP = ...
IP_PROTO_CMTP = ...
IP_PROTO_TPPP = ...
IP_PROTO_IL = ...
IP_PROTO_IP6 = ...
IP_PROTO_SDRP = ...
IP_PROTO_ROUTING = ...
IP_PROTO_FRAGMENT = ...
IP_PROTO_RSVP = ...
IP_PROTO_GRE = ...
IP_PROTO_MHRP = ...
IP_PROTO_ENA = ...
IP_PROTO_ESP = ...
IP_PROTO_AH = ...
IP_PROTO_INLSP = ...
IP_PROTO_SWIPE = ...
IP_PROTO_NARP = ...
IP_PROTO_MOBILE = ...
IP_PROTO_TLSP = ...
IP_PROTO_SKIP = ...
IP_PROTO_ICMP6 = ...
IP_PROTO_NONE = ...
IP_PROTO_DSTOPTS = ...
IP_PROTO_ANYHOST = ...
IP_PROTO_CFTP = ...
IP_PROTO_ANYNET = ...
IP_PROTO_EXPAK = ...
IP_PROTO_KRYPTOLAN = ...
IP_PROTO_RVD = ...
IP_PROTO_IPPC = ...
IP_PROTO_DISTFS = ...
IP_PROTO_SATMON = ...
IP_PROTO_VISA = ...
IP_PROTO_IPCV = ...
IP_PROTO_CPNX = ...
IP_PROTO_CPHB = ...
IP_PROTO_WSN = ...
IP_PROTO_PVP = ...
IP_PROTO_BRSATMON = ...
IP_PROTO_SUNND = ...
IP_PROTO_WBMON = ...
IP_PROTO_WBEXPAK = ...
IP_PROTO_EON = ...
IP_PROTO_VMTP = ...
IP_PROTO_SVMTP = ...
IP_PROTO_VINES = ...
IP_PROTO_TTP = ...
IP_PROTO_NSFIGP = ...
IP_PROTO_DGP = ...
IP_PROTO_TCF = ...
IP_PROTO_EIGRP = ...
IP_PROTO_OSPF = ...
IP_PROTO_SPRITERPC = ...
IP_PROTO_LARP = ...
IP_PROTO_MTP = ...
IP_PROTO_AX25 = ...
IP_PROTO_IPIPENCAP = ...
IP_PROTO_MICP = ...
IP_PROTO_SCCSP = ...
IP_PROTO_ETHERIP = ...
IP_PROTO_ENCAP = ...
IP_PROTO_ANYENC = ...
IP_PROTO_GMTP = ...
IP_PROTO_IFMP = ...
IP_PROTO_PNNI = ...
IP_PROTO_PIM = ...
IP_PROTO_ARIS = ...
IP_PROTO_SCPS = ...
IP_PROTO_QNX = ...
IP_PROTO_AN = ...
IP_PROTO_IPCOMP = ...
IP_PROTO_SNP = ...
IP_PROTO_COMPAQPEER = ...
IP_PROTO_IPXIP = ...
IP_PROTO_VRRP = ...
IP_PROTO_PGM = ...
IP_PROTO_ANY0HOP = ...
IP_PROTO_L2TP = ...
IP_PROTO_DDX = ...
IP_PROTO_IATP = ...
IP_PROTO_STP = ...
IP_PROTO_SRP = ...
IP_PROTO_UTI = ...
IP_PROTO_SMP = ...
IP_PROTO_SM = ...
IP_PROTO_PTP = ...
IP_PROTO_ISIS = ...
IP_PROTO_FIRE = ...
IP_PROTO_CRTP = ...
IP_PROTO_CRUDP = ...
IP_PROTO_SSCOPMCE = ...
IP_PROTO_IPLT = ...
IP_PROTO_SPS = ...
IP_PROTO_PIPE = ...
IP_PROTO_SCTP = ...
IP_PROTO_FC = ...
IP_PROTO_RSVPIGN = ...
IP_PROTO_RAW = ...
IP_PROTO_RESERVED = ...
IP_PROTO_MAX = ...
def test_ip(): # -> None:
    ...

def test_dict(): # -> None:
    ...

def test_hl(): # -> None:
    ...

def test_opt(): # -> None:
    ...

def test_iplen(): # -> None:
    ...

def test_zerolen(): # -> None:
    ...

def test_constuctor(): # -> None:
    ...

def test_frag(): # -> None:
    ...

def test_property_setters(): # -> None:
    ...

def test_default_udp_checksum(): # -> None:
    ...

def test_get_proto_name(): # -> None:
    ...
