"""
This type stub file was generated by pyright.
"""

from . import dpkt

class LLC(dpkt.Packet):
    """802.2 Logical Link Control (LLC) data communication protocol.

    Attributes:
        __hdr__ = (
            ('dsap', 'B', 0xaa),   # Destination Service Access Point
            ('ssap', 'B', 0xaa),   # Source Service Access Point
            ('ctl', 'B', 3)        # Control Byte
        )
    """
    __hdr__ = ...
    @property
    def is_snap(self):
        ...
    
    def unpack(self, buf): # -> None:
        ...
    
    def pack_hdr(self): # -> bytes:
        ...
    
    def __len__(self):
        ...
    


def test_llc(): # -> None:
    ...

def test_unpack_sap_ip(): # -> None:
    ...

def test_unpack_exception_handling(): # -> None:
    ...

def test_pack_hdr_invalid_class(): # -> None:
    class InvalidClass(dpkt.Packet):
        ...
    
    

