"""
This type stub file was generated by pyright.
"""

from . import dpkt

"""Platform-dependent loopback header."""
class Loopback(dpkt.Packet):
    """Platform-dependent loopback header.

    TODO: Longer class information....

    Attributes:
        __hdr__: Header fields of Loopback.
        TODO.
    """
    __hdr__ = ...
    __byte_order__ = ...
    def unpack(self, buf): # -> None:
        ...
    


def test_ethernet_unpack(): # -> None:
    ...

def test_ip_unpack(): # -> None:
    ...

def test_ip6_unpack(): # -> None:
    ...

