

from . import dpkt

"""Network Time Protocol."""
NO_WARNING = ...
LAST_MINUTE_61_SECONDS = ...
LAST_MINUTE_59_SECONDS = ...
ALARM_CONDITION = ...
RESERVED = ...
SYMMETRIC_ACTIVE = ...
SYMMETRIC_PASSIVE = ...
CLIENT = ...
SERVER = ...
BROADCAST = ...
CONTROL_MESSAGE = ...
PRIVATE = ...
class NTP(dpkt.Packet):

    __hdr__ = ...
    __bit_fields__ = ...


__s = ...
def test_ntp_pack(): # -> None:
    ...

def test_ntp_unpack(): # -> None:
    ...
