"""
This type stub file was generated by pyright.
"""

from . import dpkt

"""Open Shortest Path First."""
AUTH_NONE = ...
AUTH_PASSWORD = ...
AUTH_CRYPTO = ...
class OSPF(dpkt.Packet):
    """Open Shortest Path First.

    TODO: Longer class information....

    Attributes:
        __hdr__: Header fields of OSPF.
        TODO.
    """
    __hdr__ = ...
    def __bytes__(self): # -> bytes:
        ...
    


def test_creation(): # -> None:
    ...

