

from . import dpkt, ppp

"""PPP-over-Ethernet."""
PPPoE_PADI = ...
PPPoE_PADO = ...
PPPoE_PADR = ...
PPPoE_PADS = ...
PPPoE_PADT = ...
PPPoE_SESSION = ...
class PPPoE(dpkt.Packet):

    __hdr__ = ...
    __bit_fields__ = ...
    def unpack(self, buf): # -> None:
        ...



class PPP(ppp.PPP):
    __hdr__ = ...
    def unpack(self, buf): # -> None:
        ...

    def pack_hdr(self): # -> bytes:
        ...



def test_pppoe_discovery(): # -> None:
    ...

def test_pppoe_session(): # -> None:
    ...

def test_ppp_packing(): # -> None:
    ...

def test_ppp_short(): # -> None:
    ...

def test_pppoe_properties(): # -> None:
    ...

def test_pppoe_unpack_error(): # -> None:
    ...

def test_ppp_pack_hdr(): # -> None:
    ...
