"""
This type stub file was generated by pyright.
"""

from . import dpkt, ppp

"""PPP-over-Ethernet."""
PPPoE_PADI = ...
PPPoE_PADO = ...
PPPoE_PADR = ...
PPPoE_PADS = ...
PPPoE_PADT = ...
PPPoE_SESSION = ...
class PPPoE(dpkt.Packet):
    """PPP-over-Ethernet.

    The Point-to-Point Protocol over Ethernet (PPPoE) is a network protocol for encapsulating Point-to-Point Protocol
    (PPP) frames inside Ethernet frames. It appeared in 1999, in the context of the boom of DSL as the solution for
    tunneling packets over the DSL connection to the ISP's IP network, and from there to the rest of the Internet.

    Attributes:
        __hdr__: Header fields of PPPoE.
        _v_type:
            v: (int): Version (4 bits)
            type: (int): Type (4 bits)
        code: (int): Code. (1 byte)
        session: (int): Session ID. (2 bytes)
        len: (int): Payload length. (2 bytes)
    """
    __hdr__ = ...
    __bit_fields__ = ...
    def unpack(self, buf): # -> None:
        ...
    


class PPP(ppp.PPP):
    __hdr__ = ...
    def unpack(self, buf): # -> None:
        ...
    
    def pack_hdr(self): # -> bytes:
        ...
    


def test_pppoe_discovery(): # -> None:
    ...

def test_pppoe_session(): # -> None:
    ...

def test_ppp_packing(): # -> None:
    ...

def test_ppp_short(): # -> None:
    ...

def test_pppoe_properties(): # -> None:
    ...

def test_pppoe_unpack_error(): # -> None:
    ...

def test_ppp_pack_hdr(): # -> None:
    ...

