

from . import dpkt

"""Remote Framebuffer Protocol."""
CLIENT_SET_PIXEL_FORMAT = ...
CLIENT_SET_ENCODINGS = ...
CLIENT_FRAMEBUFFER_UPDATE_REQUEST = ...
CLIENT_KEY_EVENT = ...
CLIENT_POINTER_EVENT = ...
CLIENT_CUT_TEXT = ...
SERVER_FRAMEBUFFER_UPDATE = ...
SERVER_SET_COLOUR_MAP_ENTRIES = ...
SERVER_BELL = ...
SERVER_CUT_TEXT = ...
class RFB(dpkt.Packet):

    __hdr__ = ...


class SetPixelFormat(dpkt.Packet):
    __hdr__ = ...


class SetEncodings(dpkt.Packet):
    __hdr__ = ...


class FramebufferUpdateRequest(dpkt.Packet):
    __hdr__ = ...


class KeyEvent(dpkt.Packet):
    __hdr__ = ...


class PointerEvent(dpkt.Packet):
    __hdr__ = ...


class FramebufferUpdate(dpkt.Packet):
    __hdr__ = ...


class SetColourMapEntries(dpkt.Packet):
    __hdr__ = ...


class CutText(dpkt.Packet):
    __hdr__ = ...
