"""
This type stub file was generated by pyright.
"""

from . import dpkt

"""Routing Information Protocol."""
REQUEST = ...
RESPONSE = ...
class RIP(dpkt.Packet):
    """Routing Information Protocol.

    TODO: Longer class information....

    Attributes:
        __hdr__: Header fields of RIP.
        TODO.
    """
    __hdr__ = ...
    def unpack(self, buf): # -> None:
        ...
    
    def __len__(self):
        ...
    
    def __bytes__(self): # -> bytes:
        ...
    


class RTE(dpkt.Packet):
    __hdr__ = ...


class Auth(dpkt.Packet):
    __hdr__ = ...


def test_creation_with_auth(): # -> None:
    ...

