"""
This type stub file was generated by pyright.
"""

from . import http

"""Session Initiation Protocol."""
class Request(http.Request):
    """SIP request.

    TODO: Longer class information....

    Attributes:
        __hdr__: Header fields of SIP request.
        TODO.
    """
    __hdr_defaults__ = ...
    __methods = ...
    __proto = ...


class Response(http.Response):
    """SIP response.

    TODO: Longer class information....

    Attributes:
        __hdr__: Header fields of SIP response.
        TODO.
    """
    __hdr_defaults__ = ...
    __proto = ...


