"""
This type stub file was generated by pyright.
"""

from . import dpkt

"""Linux libpcap "cooked" capture encapsulation."""
class SLL(dpkt.Packet):
    """Linux libpcap "cooked" capture encapsulation.

    TODO: Longer class information....

    Attributes:
        __hdr__: Header fields of SLL.
        TODO.
    """
    __hdr__ = ...
    _typesw = ...
    def unpack(self, buf): # -> None:
        ...
    


def test_sll(): # -> None:
    ...

