"""
This type stub file was generated by pyright.
"""

from . import dpkt

"""Linux libpcap "cooked v2" capture encapsulation."""
class SLL2(dpkt.Packet):
    """Linux libpcap "cooked v2" capture encapsulation.

    See https://www.tcpdump.org/linktypes/LINKTYPE_LINUX_SLL2.html

    Attributes:
        __hdr__: Header fields of SLLv2.
    """
    __hdr__ = ...
    _typesw = ...
    def unpack(self, buf): # -> None:
        ...
    


def test_sll2(): # -> None:
    ...

