

from . import dpkt

"""Server Message Block."""
SMB_FLAGS_LOCK_AND_READ_OK = ...
SMB_FLAGS_BUF_AVAIL = ...
SMB_FLAGS_CASE_INSENSITIVE = ...
SMB_FLAGS_CANONICALIZED_PATHS = ...
SMB_FLAGS_OPLOCK = ...
SMB_FLAGS_OPBATCH = ...
SMB_FLAGS_REPLY = ...
SMB_FLAGS2_LONG_NAMES = ...
SMB_FLAGS2_EXTENDED_ATTRIBUTES = ...
SMB_FLAGS2_SECURITY_SIGNATURES = ...
SMB_FLAGS2_COMPRESSED = ...
SMB_FLAGS2_SECURITY_SIGNATURES_REQUIRED = ...
SMB_FLAGS2_IS_LONG_NAME = ...
SMB_FLAGS2_REVERSE_PATH = ...
SMB_FLAGS2_EXTENDED_SECURITY = ...
SMB_FLAGS2_DFS = ...
SMB_FLAGS2_PAGING_IO = ...
SMB_FLAGS2_NT_STATUS = ...
SMB_FLAGS2_UNICODE = ...
SMB_STATUS_SUCCESS = ...
class SMB(dpkt.Packet):

    __byte_order__ = ...
    __hdr__ = ...
    @property
    def pid(self):
        ...

    @pid.setter
    def pid(self, v): # -> None:
        ...



def test_smb(): # -> None:
    ...
