"""
This type stub file was generated by pyright.
"""

"""
Nicely formatted cipher suite definitions for TLS

A list of cipher suites in the form of CipherSuite objects.
These are supposed to be immutable; don't mess with them.
"""
class CipherSuite:
    """
    Encapsulates a cipher suite.

    Members/args:
    * code: two-byte ID code, as int
    * kx: key exchange algorithm, e.g. 'RSA' or 'DHE'
    * auth: authentication algorithm, e.g. 'RSA' or 'DSS'
    * cipher: stream or block cipher algorithm, e.g. 'AES_128'
    * mode: mode of operation for block ciphers, e.g. 'CBC' or 'GCM'
    * mac: message authentication code algorithm, e.g. 'MD5' or 'SHA256'
    * name: cipher suite name as defined in the RFCs,
        e.g. 'TLS_RSA_WITH_RC4_40_MD5', can be generated by default from the
        other parameters
    * encoding: encoding algorithm, defaults to cipher+mode
    Additional members:
    * kx_auth: kx+auth algorithm, as 'KeyExchangeAlgorithm' in RFCs
    """
    def __init__(self, code, kx, auth, cipher, mode, mac, name=..., encoding=...) -> None:
        ...
    
    @property
    def kx(self):
        ...
    
    @property
    def auth(self):
        ...
    
    @property
    def kx_auth(self):
        ...
    
    @property
    def encoding(self):
        ...
    
    @property
    def name(self):
        ...
    
    def __repr__(self): # -> LiteralString:
        ...
    
    MAC_SIZES = ...
    BLOCK_SIZES = ...
    @property
    def mac_size(self): # -> int:
        """In bytes. Default to 0."""
        ...
    
    @property
    def block_size(self): # -> int | None:
        """In bytes. Default to 1."""
        ...
    
    @property
    def pfs(self): # -> bool:
        ...
    
    @property
    def aead(self): # -> bool:
        ...
    
    @property
    def anonymous(self):
        ...
    


def get_unknown_ciphersuite(code): # -> CipherSuite:
    ...

CIPHERSUITES = ...
BY_CODE = ...
BY_NAME_DICT = ...
def BY_NAME(name): # -> CipherSuite:
    ...

NULL_SUITE = ...
class TestCipherSuites:
    def test_kx(self): # -> None:
        ...
    
    def test_auth(self): # -> None:
        ...
    
    def test_pfs(self): # -> None:
        ...
    
    def test_aead(self): # -> None:
        ...
    
    def test_anonymous(self): # -> None:
        ...
    
    def test_by_name_and_code(self): # -> None:
        ...
    
    def test_repr(self): # -> None:
        ...
    


