


class CipherSuite:

    def __init__(self, code, kx, auth, cipher, mode, mac, name=..., encoding=...) -> None:
        ...

    @property
    def kx(self):
        ...

    @property
    def auth(self):
        ...

    @property
    def kx_auth(self):
        ...

    @property
    def encoding(self):
        ...

    @property
    def name(self):
        ...

    def __repr__(self): # -> LiteralString:
        ...

    MAC_SIZES = ...
    BLOCK_SIZES = ...
    @property
    def mac_size(self): # -> int:

        ...

    @property
    def block_size(self): # -> int | None:

        ...

    @property
    def pfs(self): # -> bool:
        ...

    @property
    def aead(self): # -> bool:
        ...

    @property
    def anonymous(self):
        ...



def get_unknown_ciphersuite(code): # -> CipherSuite:
    ...

CIPHERSUITES = ...
BY_CODE = ...
BY_NAME_DICT = ...
def BY_NAME(name): # -> CipherSuite:
    ...

NULL_SUITE = ...
class TestCipherSuites:
    def test_kx(self): # -> None:
        ...

    def test_auth(self): # -> None:
        ...

    def test_pfs(self): # -> None:
        ...

    def test_aead(self): # -> None:
        ...

    def test_anonymous(self): # -> None:
        ...

    def test_by_name_and_code(self): # -> None:
        ...

    def test_repr(self): # -> None:
        ...
