

from . import dpkt

"""Simple Traversal of UDP through NAT."""
BINDING_REQUEST = ...
BINDING_RESPONSE = ...
BINDING_ERROR_RESPONSE = ...
SHARED_SECRET_REQUEST = ...
SHARED_SECRET_RESPONSE = ...
SHARED_SECRET_ERROR_RESPONSE = ...
MAPPED_ADDRESS = ...
RESPONSE_ADDRESS = ...
CHANGE_REQUEST = ...
SOURCE_ADDRESS = ...
CHANGED_ADDRESS = ...
USERNAME = ...
PASSWORD = ...
MESSAGE_INTEGRITY = ...
ERROR_CODE = ...
UNKNOWN_ATTRIBUTES = ...
REFLECTED_FROM = ...
class STUN(dpkt.Packet):

    __hdr__ = ...


def tlv(buf): # -> tuple[Any, Any, Any, Any]:
    ...

def parse_attrs(buf): # -> list[Any]:

    ...

def test_stun_response(): # -> None:
    ...

def test_stun_padded(): # -> None:
    ...
