

from . import dpkt

"""Transmission Control Protocol."""
TH_FIN = ...
TH_SYN = ...
TH_RST = ...
TH_PUSH = ...
TH_ACK = ...
TH_URG = ...
TH_ECE = ...
TH_CWR = ...
TH_NS = ...
TCP_PORT_MAX = ...
TCP_WIN_MAX = ...
def tcp_flags_to_str(val): # -> LiteralString:
    ...

class TCP(dpkt.Packet):

    __hdr__ = ...
    __bit_fields__ = ...
    __pprint_funcs__ = ...
    opts = ...
    def __len__(self):
        ...

    def __bytes__(self): # -> bytes:
        ...

    def unpack(self, buf): # -> None:
        ...



TCP_OPT_EOL = ...
TCP_OPT_NOP = ...
TCP_OPT_MSS = ...
TCP_OPT_WSCALE = ...
TCP_OPT_SACKOK = ...
TCP_OPT_SACK = ...
TCP_OPT_ECHO = ...
TCP_OPT_ECHOREPLY = ...
TCP_OPT_TIMESTAMP = ...
TCP_OPT_POCONN = ...
TCP_OPT_POSVC = ...
TCP_OPT_CC = ...
TCP_OPT_CCNEW = ...
TCP_OPT_CCECHO = ...
TCP_OPT_ALTSUM = ...
TCP_OPT_ALTSUMDATA = ...
TCP_OPT_SKEETER = ...
TCP_OPT_BUBBA = ...
TCP_OPT_TRAILSUM = ...
TCP_OPT_MD5 = ...
TCP_OPT_SCPS = ...
TCP_OPT_SNACK = ...
TCP_OPT_REC = ...
TCP_OPT_CORRUPT = ...
TCP_OPT_SNAP = ...
TCP_OPT_TCPCOMP = ...
TCP_OPT_MAX = ...
def parse_opts(buf): # -> list[Any]:

    ...

def test_parse_opts(): # -> None:
    ...

def test_offset(): # -> None:
    ...

def test_tcp_flags_to_str(): # -> None:
    ...

def test_tcp_unpack(): # -> None:
    ...

def test_tcp_pack(): # -> None:
    ...
