"""
This type stub file was generated by pyright.
"""

from . import dpkt

"""Transparent Network Substrate."""
class TNS(dpkt.Packet):
    """Transparent Network Substrate.

    TODO: Longer class information....

    Attributes:
        __hdr__: Header fields of TNS.
        TODO.
    """
    __hdr__ = ...
    def unpack(self, buf): # -> None:
        ...
    


def test_tns(): # -> None:
    ...

