"""
This type stub file was generated by pyright.
"""

from . import dpkt

"""ISO Transport Service on top of the TCP (TPKT)."""
class TPKT(dpkt.Packet):
    """ISO Transport Service on top of the TCP (TPKT).

    "Emulate" ISO transport services COTP on top of TCP. The two major points missing in TCP (compared to COTP)
    are the TSAP addressing and the detection of packet boundaries on the receiving host.

    Attributes:
        __hdr__: Header fields of TPKT.
            v: (int): Version (1 byte)
            rsvd: (int): Reserved (1 byte)
            len: (int): Packet Length (2 bytes)
    """
    __hdr__ = ...


