"""
This type stub file was generated by pyright.
"""

from . import dpkt

"""User Datagram Protocol."""
UDP_HDR_LEN = ...
UDP_PORT_MAX = ...
class UDP(dpkt.Packet):
    """User Datagram Protocol.

    User Datagram Protocol (UDP) is one of the core members of the Internet protocol suite.
    With UDP, computer applications can send messages, in this case referred to as datagrams,
    to other hosts on an Internet Protocol (IP) network. Prior communications are not required
    in order to set up communication channels or data paths.

    Attributes:
        __hdr__: Header fields of UDP.
            sport: (int): Source port. (2 bytes)
            dport: (int): Destination port. (2 bytes)
            ulen: (int): Length. (2 bytes)
            sum: (int): Checksum. (2 bytes)
    """
    __hdr__ = ...


