"""
This type stub file was generated by pyright.
"""

"""Various Utility Functions"""
def mac_to_str(address): # -> LiteralString:
    r"""Convert a MAC address to a readable/printable string

       Args:
           address (str): a MAC address in hex form (e.g. '\x01\x02\x03\x04\x05\x06')
       Returns:
           str: Printable/readable MAC address
    """
    ...

def inet_to_str(inet): # -> str:
    """Convert inet object to a string

        Args:
            inet (inet struct): inet network address
        Returns:
            str: Printable/readable IP address
    """
    ...

def make_dict(obj): # -> dict[Any, Any]:
    """Create a dictionary out of a non-builtin object"""
    ...

def is_builtin(obj): # -> bool:
    ...

def deprecation_warning(*args): # -> None:
    """print a deprecation warning"""
    ...

def test_utils(): # -> None:
    """Test the utility methods"""
    ...

