"""
This type stub file was generated by pyright.
"""

from . import dpkt

"""Virtual Router Redundancy Protocol."""
class VRRP(dpkt.Packet):
    """Virtual Router Redundancy Protocol.

    TODO: Longer class information....

    Attributes:
        __hdr__: Header fields of VRRP.
        TODO.
    """
    __hdr__ = ...
    __bit_fields__ = ...
    addrs = ...
    auth = ...
    def unpack(self, buf): # -> None:
        ...
    
    def __len__(self):
        ...
    
    def __bytes__(self):
        ...
    


def test_vrrp(): # -> None:
    ...

