"""
This type stub file was generated by pyright.
"""

from collections import UserDict
from sklearn.utils._repr_html.base import ReprHTMLMixin

class ParamsDict(ReprHTMLMixin, UserDict):
    """Dictionary-like class to store and provide an HTML representation.

    It builds an HTML structure to be used with Jupyter notebooks or similar
    environments. It allows storing metadata to track non-default parameters.

    Parameters
    ----------
    params : dict, default=None
        The original dictionary of parameters and their values.

    non_default : tuple
        The list of non-default parameters.
    """
    _html_repr = ...
    def __init__(self, params=..., non_default=...) -> None:
        ...
