"""
This type stub file was generated by pyright.
"""

"""
Pytest runner that allows test to be run within python
"""
class PytestTester:
    def __init__(self, package_path=...) -> None:
        ...

    def __call__(self, extra_args=..., exit=...): # -> bool:
        ...
