"""
This type stub file was generated by pyright.
"""

def safe_version(module, attr=..., *others): # -> Any | Literal['Cannot detect version']:
    ...

def show_versions(show_dirs=...): # -> None:
    """
    List the versions of statsmodels and any installed dependencies

    Parameters
    ----------
    show_dirs : bool
        Flag indicating to show module locations
    """
    ...

if __name__ == "__main__":
    ...
