"""
This type stub file was generated by pyright.
"""

import numpy as np
from typing import Any, TYPE_CHECKING, Union
from collections.abc import Sequence
from pandas import DataFrame, Series
from numpy.typing import NDArray, _FloatLike_co, _UIntLike_co

if TYPE_CHECKING:
    _ExtendedFloatLike_co = Union[_FloatLike_co, _UIntLike_co]
    NumericArray = NDArray[Any, np.dtype[_ExtendedFloatLike_co]]
    Float64Array = NDArray[Any, np.double]
    ArrayLike1D = Union[Sequence[Union[float, int]], NumericArray, Series]
    ArrayLike2D = Union[Sequence[Sequence[Union[float, int]]], NumericArray, DataFrame]
else:
    ...
__all__ = ["ArrayLike", "DTypeLike", "Float64Array", "ArrayLike1D", "ArrayLike2D", "NDArray", "NumericArray"]
